CONF_THRESHOLD: 25
DEBUG_MODE: true
DEBUG_RECT_OUTLINE_COLOR: blue
DEBUG_RECT_OUTLINE_WIDTH: 1
HIGHLIGHT_RECT_OUTLINE_COLOR: red
HIGHLIGHT_RECT_OUTLINE_WIDTH: 2
LOG_LEVEL: INFO
OCR_FPS: 2.0
OCR_LANGUAGE: eng
PAR_CONF_THRESHOLD: 50
STOP_HOTKEY: <alt>+c
TESSERACT_CMD: D:\Program Files\Tesseract-OCR\tesseract.exe
UI_UPDATE_INTERVAL: 100
# Translation settings
TRANSLATION_ENABLED: true
TRANSLATION_CACHE_SIZE: 1000
TRANSLATION_CACHE_TTL: 3600
TRANSLATION_MAX_RETRIES: 3
TRANSLATION_RETRY_DELAY: 1.0
TRANSLATION_TARGET_LANG: zh-cn
TRANSLATION_SOURCE_LANG: en
TRANSLATION_HOTKEY: <alt>+t
